apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
    app: node-problem-detector
spec:
  selector:
    matchLabels:
      app: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
      - name: node-problem-detector
        command:
        - /node-problem-detector
        - --logtostderr
        - --config.system-log-monitor=/config/kernel-monitor.json #,/config/docker-monitor.json
        - --config.custom-plugin-monitor=config/custom-scheduledevents-plugin-monitor.json,config/custom-scheduledevents-preempt-plugin-monitor.json
        #image: k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.7
        image: cljshafer/node-problem-detector:v0.8.8-2-gf27c3a8-dirty
        resources:
          limits:
            cpu: 10m
            memory: 80Mi
          requests:
            cpu: 10m
            memory: 80Mi
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: config
          mountPath: /config
          readOnly: false
        - name: config-plugin
          mountPath: /config/plugin
          readOnly: false
        - name: curl
          mountPath: /usr/bin/curl
          readOnly: false
        - name: jq
          mountPath: /usr/bin/jq
          readOnly: false

      volumes:
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log/
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: curl
        hostPath:
          path: /usr/bin/curl
      - name: jq
        hostPath:
          path: /usr/bin/jq
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          name: node-problem-detector-config
          items:
          - key: kernel-monitor.json
            path: kernel-monitor.json
          - key: docker-monitor.json
            path: docker-monitor.json
          - key: custom-scheduledevents-plugin-monitor.json
            path: custom-scheduledevents-plugin-monitor.json
          - key: custom-scheduledevents-preempt-plugin-monitor.json
            path: custom-scheduledevents-preempt-plugin-monitor.json
      - name: config-plugin
        configMap:
          name: node-problem-detector-config
          defaultMode: 0777
          items:
          - key: check_scheduledevent.sh
            path: check_scheduledevent.sh
          - key: check_freeze.sh
            path: check_freeze.sh
          - key: check_preempt.sh
            path: check_preempt.sh
          - key: check_reboot.sh
            path: check_reboot.sh
          - key: check_redeploy.sh
            path: check_redeploy.sh
          - key: check_terminate.sh
            path: check_terminate.sh
          - key: fakeIMDS.sh
            path: fakeIMDS.sh


      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
